/*Modelagem básica - ENTIDADE IGUAL TABELA 
CAMPOS SÃO ATRIBUTOS 
*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO (11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(11)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* Processo de modelagem  */

/* FASE E 1 E 2 - AD ADM DE DADOS*/

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM 

/* FASE 3 - DBA 	/ AD */

MODELAGEM FÍSICA - SCRIPT DE BANCO 

/* INICIANDO MODELAGEM FÍSICA*/

CREATE DATABASE PROJETO;

--CONECTAR AO BANCO DE DADOS 

USE PROJETO;

--CRIAR BANCO DE DODOS 

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR (100)
):

--MOSTRAR TABELA 

SHOW TABLES;

--DESCOBRINDO A ESTRUTURA DE UMA TABELA
DESC CLIENTE;

+----------+--------------+------+-----+---------+-------+
| Field    | Type         | Null | Key | Default | Extra |
+----------+--------------+------+-----+---------+-------+
| NOME     | varchar(30)  | YES  |     | NULL    |       |
| SEXO     | char(1)      | YES  |     | NULL    |       |
| EMAIL    | varchar(30)  | YES  |     | NULL    |       |
| CPF      | int(11)      | YES  |     | NULL    |       |
| TELEFONE | varchar(30)  | YES  |     | NULL    |       |
| ENDERECO | varchar(100) | YES  |     | NULL    |       |
+----------+--------------+------+-----+---------+-------+

SELECT NOW(); 
+---------------------+
| NOW()               |
+---------------------+
| 2023-10-02 01:53:10 |
+---------------------+

SELECT NOW() AS DATA_HORA; --MOSTRA O NOW EM UMA COLUNA 
+---------------------+
| DATA_HORA           |
+---------------------+
| 2023-10-02 01:53:28 |
+---------------------+

--Sintaxe basica para inserção
INSERT INTO TABELA

--INSERIR DA MANEIRA CORRRETA FALA CAMPO E INFORMA O VALOR PARA NÃO OCORRER ERROS

INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES ('LUCAS1', 'M', 'LUCAS@EMAIL.COM', 444484599, '4181566552', 'ENDERECO DE CASA');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES ('LUCAS2', 'M', 'LUCAS@EMAIL.COM', 488484599, '4180566552', 'ENDERECO DE CASA');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES ('LUCAS3', 'M', 'LUCAS@EMAIL.COM', 844484599, '4188564552', 'ENDERECO DE CASA');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES ('LUCAS4', 'M', 'LUCAS@EMAIL.COM', 484848459, '4186566552', 'ENDERECO DE CASA');


SELECT 'LUCAS' AS ESTUDANTE; --MOSTRA LUCAS COMO UM DADO DE ESTUDANTE	
+-----------+
| ESTUDANTE |
+-----------+
| LUCAS     |
+-----------+

--MOSTRAR COLUNA DE UMA TABELA

SELECT COLUNA FROM TABELA;
SELECT NOME FROM CLIENTE;
+--------+
| NOME   |
+--------+
| lucas6 |
| LUCAS1 |
| LUCAS2 |
| LUCAS3 |
| LUCAS4 |
| LUCAS5 |
| LUCAS1 |
+--------+

--MUDAR NOME DE COLUNA PARA CONSULTA

SELECT COLUNA AS NOME NOVO FROM CLIENTE;
SELECT NOME AS CLIENTE, EMAIL, SEXO FROM CLIENTE;
+---------+------------------+------+
| CLIENTE | EMAIL            | SEXO |
+---------+------------------+------+
| lucas6  | lucas1@gmail.com | M    |
| LUCAS1  | LUCAS1@EMAIL.COM | M    |
| LUCAS2  | LUCAS2@EMAIL.COM | M    |
| LUCAS3  | LUCAS3@EMAIL.COM | M    |
| LUCAS4  | LUCAS4@EMAIL.COM | M    |
| LUCAS5  | LUCAS5@EMAIL.COM | M    |
| LUCAS1  | LUCAS1@EMAIL.COM | M    |
+---------+------------------+------+


SELECT NOME AS CLIENTE, EMAIL AS ENDERECO_ELETRONICO, FROM CLIENTE; 
+---------+------------------+------+
| CLIENTE | EMAIL            | SEXO |
+---------+------------------+------+
| lucas6  | lucas1@gmail.com | M    |
| LUCAS1  | LUCAS1@EMAIL.COM | M    |
| LUCAS2  | LUCAS2@EMAIL.COM | M    |
| LUCAS3  | LUCAS3@EMAIL.COM | M    |
| LUCAS4  | LUCAS4@EMAIL.COM | M    |
| LUCAS5  | LUCAS5@EMAIL.COM | M    |
| LUCAS1  | LUCAS1@EMAIL.COM | M    |
+---------+------------------+------+

--NÃO USAR ***************

--WHERE FILTRA = EXATO FILTAR LINHA WHERE FILTRA DADO DE UMA COLUNA  

--MOSTRA NOME E ENDERECO FILTRADO POR SEXO = M
SELECT NOME AS CLIENTE, ENDERECO FROM CLIENTE
WHERE SEXO = 'M';

+---------+------------------+
| CLIENTE | ENDERECO         |
+---------+------------------+
| lucas6  | ENDERECO DE CASA |
| LUCAS1  | ENDERECO DE CASA |
| LUCAS2  | ENDERECO DE CASA |
| LUCAS3  | ENDERECO DE CASA |
| LUCAS4  | ENDERECO DE CASA |
| LUCAS5  | ENDERECO DE CASA |
| LUCAS1  | ENDERECO DE CASA |
+---------+------------------+

--SE EMPTY SET É CAMPO VAZIO 

-- lIKE FILTRA ALGO EXEMPLO INICIO MEIO FIM
 
-- %QUALQUER COISA  

-- LIKE BUSCA ALGO 

SELECT NOME AS CLIENTE, ENDERECO FROM CLIENTE
WHERE TELEFONE LIKE '%2';

+---------+------------------+
| CLIENTE | ENDERECO         |
+---------+------------------+
| lucas6  | ENDERECO DE CASA |
| LUCAS1  | ENDERECO DE CASA |
| LUCAS2  | ENDERECO DE CASA |
| LUCAS3  | ENDERECO DE CASA |
| LUCAS4  | ENDERECO DE CASA |
| LUCAS5  | ENDERECO DE CASA |
| LUCAS1  | ENDERECO DE CASA |
+---------+------------------+

--FILTRA OS QUE TERMINAM COM NUMERO 2

SELECT NOME AS CLIENTE, ENDERECO FROM CLIENTE
WHERE TELEFONE LIKE '2%';

--FILTRA QUE COMEÇA COM COM 2

SELECT NOME AS CLIENTE, ENDERECO FROM CLIENTE
WHERE TELEFONE LIKE '%2%';

--FILTRA OS QUE TEM 2 NO MEIO

JUNÇÃO DE BUSCA 
UTILIZA AND E OR 


/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

+--------+------------+
| NOME   | TELEFONE   |
+--------+------------+
| lucas6 | 4181566552 |
| LUCAS1 | 4181566552 |
| LUCAS2 | 4181566552 |
| LUCAS3 | 4181566552 |
| LUCAS4 | 4181566552 |
| LUCAS5 | 4181566552 |
| LUCAS1 | 4181566552 |
+--------+------------+

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

+--------+------+
| NOME   | SEXO |
+--------+------+
| lucas6 | M    |
| LUCAS1 | M    |
| LUCAS2 | M    |
| LUCAS3 | M    |
| LUCAS4 | M    |
| LUCAS5 | M    |
| LUCAS1 | M    |
+--------+------+

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE NOME = 'LUCAS';

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CASA';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'CASA%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CASA%';
+--------+------+------------------+
| NOME   | SEXO | ENDERECO         |
+--------+------+------------------+
| lucas6 | M    | ENDERECO DE CASA |
| LUCAS1 | M    | ENDERECO DE CASA |
| LUCAS2 | M    | ENDERECO DE CASA |
| LUCAS3 | M    | ENDERECO DE CASA |
| LUCAS4 | M    | ENDERECO DE CASA |
| LUCAS5 | M    | ENDERECO DE CASA |
| LUCAS1 | M    | ENDERECO DE CASA |
+--------+------+------------------+
